import { notFound } from "next/navigation";
import { ArrowLeft, ChevronRight, Trophy } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { FlagIcon } from "@/components/flag-icon";
import { editions, getEdition } from "@/lib/history";
import { slugify } from "@/lib/players";

const codes: Record<string, string> = { "Greet Minnen":"BEL", "Petra Marčinko":"CRO", "Manon Léonard":"FRA", "Tessah Andrianjafitrimo":"FRA", "Céline Naef":"SUI", "Alina Korneeva":"RUS", "Jaqueline Cristian":"ROU", "Magali Kempen":"BEL", "Mihaela Buzărnescu":"ROU", "Anna Bondár":"HUN", "Alyssa Réguer":"FRA", "Mathilde Lollia":"FRA", "Ayana Akli":"USA", "Daria Snigur":"UKR", "Tamira Paszek":"AUT", "Amarni Banks":"GBR", "Mio Kawamura":"JPN", "Lucía Cortez Llorca":"ESP", "Jenny Lim":"FRA", "Océane Dodin":"FRA", "Sonay Kartal":"GBR", "Marine Partaud":"FRA", "Ysaline Bonaventure":"BEL", "Harmony Tan":"FRA", "Ylena In-Albon":"SUI", "Lucie Nguyen Tan":"FRA", "Arianne Hartono":"NED" };
function Player({ name, link = false }: { name: string; link?: boolean }) { const content = <span className="inline-flex items-center gap-2 align-middle"><FlagIcon code={codes[name] || "N/C"}/><span><b>{name}</b><small className="ml-1 text-[10px] font-black text-[#68766f]">{codes[name] || "N/C"}</small></span></span>; return link ? <a href={`/joueuses/${slugify(name)}`} className="hover:text-[#197c57]">{content}</a> : content; }
export function generateStaticParams() { return editions.map((e) => ({ year: String(e.year) })); }

export default async function EditionPage({ params }: { params: Promise<{ year: string }> }) { const { year } = await params; const e = getEdition(year); if (!e) notFound(); return <main><SiteHeader/><div className="mx-auto max-w-[1050px] px-5 py-12"><a href="/historique" className="inline-flex items-center gap-2 font-bold"><ArrowLeft size={17}/> Toutes les éditions</a><div className="mt-8 overflow-hidden rounded-[2rem] bg-[#0b3427] p-8 text-white sm:p-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#d9f13b]">{e.category} · édition {e.year}</p><h1 className="mt-4 text-5xl font-black sm:text-7xl"><Player name={e.single.name} link/></h1><p className="mt-5 text-lg text-white/65">Championne du simple · victoire en finale face à <Player name={e.single.runnerUp}/></p><a href={`/joueuses/${slugify(e.single.name)}`} className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#d9f13b] px-5 py-3 font-bold text-[#082b20]">Voir sa fiche joueuse <ChevronRight size={17}/></a></div><section className="mt-12"><p className="eyebrow">Cinq étapes vers le titre</p><h2>Son parcours</h2><div className="mt-8 space-y-3">{e.route.map((m, i) => <div key={m.round} className="grid gap-3 rounded-2xl border border-[#dce3dd] bg-white p-5 sm:grid-cols-[50px_140px_1fr_auto] sm:items-center"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#d9f13b] font-black">{i + 1}</span><b>{m.round}</b><span>victoire face à <Player name={m.opponent}/></span><span className="font-mono text-[#197c57]">{m.score}</span></div>)}</div></section><section className="mt-12 grid gap-5 md:grid-cols-2"><div className="rounded-[1.5rem] bg-white p-7"><Trophy className="text-[#197c57]"/><h3 className="mt-8 text-2xl font-black">Finale du simple</h3><p className="mt-3"><Player name={e.single.name}/> bat <Player name={e.single.runnerUp}/></p><b className="mt-2 block text-xl">{e.single.score}</b></div><div className="rounded-[1.5rem] bg-[#d9f13b] p-7"><h3 className="text-2xl font-black">Championnes du double</h3><p className="mt-4 font-bold">{e.doubles.names}</p><p className="mt-2 text-sm">battent {e.doubles.runnerUp}</p><b className="mt-2 block">{e.doubles.score}</b></div></section></div><SiteFooter/></main>; }
