export type Edition={year:number;category:string;single:{name:string;flag:string;runnerUp:string;score:string};doubles:{names:string;runnerUp:string;score:string};route:Array<{round:string;opponent:string;score:string}>};
export const editions:Edition[]=[
{year:2025,category:"W75",single:{name:"Greet Minnen",flag:"🇧🇪",runnerUp:"Petra Marčinko",score:"6–2, 6–1"},doubles:{names:"Naiktha Bains / Rutuja Bhosale",runnerUp:"Polina Iatcenko / Sofya Lansere",score:"6–2, 1–6, [10–6]"},route:[{round:"1er tour",opponent:"Alyssa Réguer",score:"6–0, 6–1"},{round:"2e tour",opponent:"Mathilde Lollia",score:"7–5, 6–3"},{round:"Quart",opponent:"Tessah Andrianjafitrimo",score:"6–1, 7–5"},{round:"Demi-finale",opponent:"Polina Iatcenko",score:"4–6, 6–2, 6–1"},{round:"Finale",opponent:"Petra Marčinko",score:"6–2, 6–1"}]},
{year:2024,category:"W75",single:{name:"Tessah Andrianjafitrimo",flag:"🇫🇷",runnerUp:"Manon Léonard",score:"6–2, 6–4"},doubles:{names:"Lina Glushko / Anastasia Tikhonova",runnerUp:"Julia Avdeeva / Ekaterina Maklakova",score:"6–3, 6–1"},route:[{round:"1er tour",opponent:"Ayana Akli",score:"6–4, 6–4"},{round:"2e tour",opponent:"Daria Snigur",score:"6–4, 2–6, 6–3"},{round:"Quart",opponent:"Tamira Paszek",score:"6–1, 6–7(5), 6–2"},{round:"Demi-finale",opponent:"Amarni Banks",score:"6–0, 2–6, 6–4"},{round:"Finale",opponent:"Manon Léonard",score:"6–2, 6–4"}]},
{year:2023,category:"W80+H",single:{name:"Céline Naef",flag:"🇨🇭",runnerUp:"Alina Korneeva",score:"4–6, 6–2, 7–6(9–7)"},doubles:{names:"Fiona Ferro / Alina Korneeva",runnerUp:"Maryna Kolb / Nadiia Kolb",score:"7–6(9–7), 7–5"},route:[{round:"1er tour",opponent:"Mio Kawamura",score:"6–2, 6–1"},{round:"2e tour",opponent:"Lucía Cortez Llorca",score:"7–5, 6–1"},{round:"Quart",opponent:"Jenny Lim",score:"5–7, 6–1, 7–5"},{round:"Demi-finale",opponent:"Océane Dodin",score:"Forfait"},{round:"Finale",opponent:"Alina Korneeva",score:"4–6, 6–2, 7–6(9–7)"}]},
{year:2022,category:"W80+H",single:{name:"Jaqueline Cristian",flag:"🇷🇴",runnerUp:"Magali Kempen",score:"6–4, 6–4"},doubles:{names:"Freya Christie / Ali Collins",runnerUp:"Weronika Falkowska / Sarah Beth Grey",score:"1–6, 7–6(7–4), [10–3]"},route:[{round:"1er tour",opponent:"Sonay Kartal",score:"6–2, 2–6, 6–3"},{round:"2e tour",opponent:"Marine Partaud",score:"4–6, 6–3, 6–1"},{round:"Quart",opponent:"Ysaline Bonaventure",score:"6–4, 1–6, 6–4"},{round:"Demi-finale",opponent:"Harmony Tan",score:"3–6, 6–4, 3–0 ab."},{round:"Finale",opponent:"Magali Kempen",score:"6–4, 6–4"}]},
{year:2021,category:"W80+H",single:{name:"Mihaela Buzărnescu",flag:"🇷🇴",runnerUp:"Anna Bondár",score:"6–1, 6–3"},doubles:{names:"Robin Anderson / Amandine Hesse",runnerUp:"Estelle Cascino / Sarah Beth Grey",score:"6–3, 7–6(7–2)"},route:[{round:"1er tour",opponent:"Ylena In-Albon",score:"6–0, 6–4"},{round:"2e tour",opponent:"Lucie Nguyen Tan",score:"6–3, 6–2"},{round:"Quart",opponent:"Amandine Hesse",score:"6–7(3), 6–2, 6–2"},{round:"Demi-finale",opponent:"Arianne Hartono",score:"6–1, 6–1"},{round:"Finale",opponent:"Anna Bondár",score:"6–1, 6–3"}]}
];
export const getEdition=(year:string)=>editions.find(e=>String(e.year)===year);
