export type Player = { pos:number; country:string; code:string; name:string; rank?:number; wtaRank?:number; wtaRankType?:"Singles"|"Doubles"; seed?:number; entry:"Wild-card"|"Tableau principal"|"Qualifications"|"Championne"; age?:number; birthDate?:string; birthPlace?:string; height?:string; careerHigh?:string; titles?:number; wonLost?:string; prizeMoney?:string; seasonPrizeMoney?:string; careerPrizeMoney?:string; careerHighlights?:string[]; wtaUrl?:string };
export const slugify=(name:string)=>name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const directBase=[
[1,"🇺🇦","UKR","Veronika Podrez",132],[2,"🇵🇱","POL","Martyna Kubka",182],[3,"","","Julia Avdeeva",185],[4,"🇨🇿","CZE","Anna Siskova",207],[5,"🇨🇭","SUI","Valentina Ryser",261],[6,"🇺🇸","USA","Fiona Crawley",264],[7,"🇬🇷","GRE","Martha Matoula",296],[8,"🇳🇱","NED","Britt Du Pree",308],[9,"🇫🇷","FRA","Manon Léonard",329],[10,"🇮🇳","IND","Sahaja Yamalapalli",342],[11,"🇬🇧","GBR","Naiktha Bains",367],[12,"🇫🇷","FRA","Yasmine Mansouri",377],[13,"🇫🇷","FRA","Tiphanie Lemaître",400],[14,"🇫🇷","FRA","Amandine Hesse",415],[15,"🇫🇷","FRA","Lucie Nguyen Tan",424],[16,"🇫🇮","FIN","Laura Hietaranta",427]] as const;
export const direct:Player[]=directBase.map(([pos,country,code,name,rank])=>({pos,country,code,name,rank,entry:"Tableau principal"}));
direct.find(p=>p.name==="Julia Avdeeva")!.code="RUS";
direct.find(p=>p.name==="Julia Avdeeva")!.country="🇷🇺";
export const wildcard:Player={pos:17,country:"🇬🇧",code:"GBR",name:"Hannah Klugman",rank:437,entry:"Wild-card",age:17};
const qualBase:Array<[string,string,string,number?,number?]>=[
["Gina Marie Dittmann","🇩🇪","GER",1,512],["Charlotte Narti","🇫🇷","FRA"],["Olivia Gram","🇩🇰","DEN"],["Stefaniya Pushkar","🇨🇭","SUI",15,950],["Anastasiia Firman","🇺🇦","UKR",2,588],["Romane Morel","🇫🇷","FRA"],["Hanna Bougouffa","🇫🇷","FRA"],["Gyeong Seo Lee","🇰🇷","KOR",9,724],["Carson Tanguilig","🇺🇸","USA",3,606],["Severine Deppner","🇩🇪","GER"],["Vicky Van de Peer","🇧🇪","BEL"],["Carolin Raschdorf","🇩🇪","GER",14,897],["Sachia Vickery","🇺🇸","USA",4,612],["Savine Erler","🇫🇷","FRA"],["Luisa Hrda","🇩🇪","GER"],["Carmen Lopez Martinez","🇪🇸","ESP",13,835],["Mathilde Lollia","🇫🇷","FRA",5,624],["Manoly Rengeard","🇫🇷","FRA"],["Katarina Kujovic","🇧🇪","BEL"],["Marine Szostak","🇫🇷","FRA",10,734],["Berta Bonardi","🇦🇷","ARG",6,661],["Seda Baslilar","🇹🇷","TUR"],["Charlotte Maurey","🇫🇷","FRA"],["Paula Cembranos","🇨🇭","SUI",11,784],["Clara Vlasselaer","🇧🇪","BEL",7,667],["Lou Borez","🇫🇷","FRA"],["Daniela Vismane","🇱🇻","LAT"],["Lian Tran","🇳🇱","NED",12,829],["Demi Tran","🇳🇱","NED",8,693],["Ashmitha Easwaramurthi","🇮🇳","IND"],["Naoko Eto","🇯🇵","JPN"],["Kim Chiarello","🇫🇷","FRA",16]];
export const officialQualifiers:Player[]=qualBase.map(([name,country,code,seed,rank],i)=>({pos:i+1,name,country,code,seed,rank,entry:"Qualifications"}));
officialQualifiers.find(p=>p.name==="Severine Deppner")!.code="FRA";
officialQualifiers.find(p=>p.name==="Severine Deppner")!.country="🇫🇷";
export const historicChampions:Player[]=[{pos:1,name:"Greet Minnen",country:"🇧🇪",code:"BEL",entry:"Championne"},{pos:1,name:"Tessah Andrianjafitrimo",country:"🇫🇷",code:"FRA",entry:"Championne"},{pos:1,name:"Céline Naef",country:"🇨🇭",code:"SUI",entry:"Championne"},{pos:1,name:"Jaqueline Cristian",country:"🇷🇴",code:"ROU",entry:"Championne"},{pos:1,name:"Mihaela Buzărnescu",country:"🇷🇴",code:"ROU",entry:"Championne"}];
const profiles:Record<string,Partial<Player>>={
 "veronika-podrez":{age:19,birthDate:"11 janvier 2007",birthPlace:"—",height:"—",careerHigh:"132",titles:0,wonLost:"31 / 16",prizeMoney:"123 192 $",careerHighlights:["Finaliste WTA en 2026 à Rouen","Trois titres ITF en 2025 : W15 Hagetmau, W15 Le Havre et W75 Poitiers","Deux titres ITF en 2024 : W15 Dinard et W15 Esch/Alzette","Premiers titres professionnels en 2023 à Cherbourg-en-Cotentin et Wanfercée-Baulet"],wtaUrl:"https://www.wtatennis.com/players/331197/veronika-podrez"},
 "hannah-klugman":{age:17,birthDate:"18 février 2009",birthPlace:"Grande-Bretagne",careerHigh:"436",titles:0},
 "sachia-vickery":{birthDate:"11 mai 1995",birthPlace:"Miramar, Floride, États-Unis",height:"1,63 m",careerHigh:"73"},
 "amandine-hesse":{birthDate:"16 janvier 1993",birthPlace:"Montauban, France",height:"1,64 m",careerHigh:"154"},
 "naiktha-bains":{birthDate:"17 décembre 1997",birthPlace:"Leeds, Grande-Bretagne",height:"1,63 m",careerHigh:"199"},
 "mihaela-buzarnescu":{birthDate:"4 mai 1988",birthPlace:"Bucarest, Roumanie",height:"1,75 m",careerHigh:"20"},
 "jaqueline-cristian":{birthDate:"5 juin 1998",birthPlace:"Bucarest, Roumanie",height:"1,82 m",careerHigh:"28"},
 "greet-minnen":{birthDate:"14 août 1997",birthPlace:"Turnhout, Belgique",height:"1,75 m",careerHigh:"59"},
 "celine-naef":{age:21,birthDate:"25 juin 2005",birthPlace:"Feusisberg, Suisse",height:"1,70 m",careerHigh:"121",titles:2,wonLost:"—",prizeMoney:"—",careerHighlights:["Championne du W75 Le Neubourg en 2023"]},
 "tessah-andrianjafitrimo":{age:27,birthDate:"27 mars 1999",birthPlace:"Montpellier, France",height:"1,68 m",careerHigh:"214",titles:1,wonLost:"—",prizeMoney:"—",careerHighlights:["Championne du W75 Le Neubourg en 2024"]}
};
const wtaProfiles:Record<string,Partial<Player>>={
 "greet-minnen":{wtaRank:72,wtaRankType:"Singles",age:29,titles:1,wonLost:"—",prizeMoney:"2 830 $",careerPrizeMoney:"3 461 222 $",careerHigh:"59",birthDate:"14 août 1997",height:"1,75 m",birthPlace:"Turnhout, Belgique"},
 "tessah-andrianjafitrimo":{wtaRank:636,wtaRankType:"Singles",age:27,titles:0,wonLost:"0 / 0",prizeMoney:"0 $",careerPrizeMoney:"673 518 $",careerHigh:"139",birthDate:"11 octobre 1998",height:"1,69 m",birthPlace:"Montpellier, France"},
 "celine-naef":{wtaRank:221,wtaRankType:"Singles",age:21,titles:0,wonLost:"28 / 12",prizeMoney:"107 784 $",careerPrizeMoney:"572 934 $",careerHigh:"121",birthDate:"25 juin 2005",height:"1,67 m",birthPlace:"Bülach, Suisse"},
 "jaqueline-cristian":{wtaRank:44,wtaRankType:"Singles",age:28,titles:1,wonLost:"—",prizeMoney:"—",careerPrizeMoney:"3 350 510 $",careerHigh:"28",birthDate:"5 juin 1998",height:"1,82 m",birthPlace:"Bucarest, Roumanie"},
 "mihaela-buzarnescu":{wtaRank:947,wtaRankType:"Singles",age:38,titles:1,wonLost:"—",prizeMoney:"0 $",careerPrizeMoney:"2 791 287 $",careerHigh:"20",birthDate:"4 mai 1988",height:"1,75 m",birthPlace:"Bucarest, Roumanie"},
 "veronika-podrez":{wtaRank:132,wtaRankType:"Singles",age:19,titles:0,wonLost:"31 / 16",prizeMoney:"123 192 $",careerHigh:"132",birthDate:"11 janvier 2007",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/331197/veronika-podrez"},
 "martyna-kubka":{wtaRank:130,wtaRankType:"Doubles",age:25,titles:0,wonLost:"25 / 10",prizeMoney:"48 553 $",careerHigh:"182",birthDate:"19 avril 2001",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/328907/martyna-kubka"},
 "julia-avdeeva":{wtaRank:185,wtaRankType:"Singles",age:24,titles:0,wonLost:"28 / 15",prizeMoney:"94 338 $",careerHigh:"177",birthDate:"6 juillet 2002",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/330102/julia-avdeeva"},
 "anna-siskova":{wtaRank:63,wtaRankType:"Doubles",age:25,titles:0,wonLost:"29 / 11",prizeMoney:"210 063 $",careerHigh:"207",birthDate:"1 juillet 2001",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/324995/anna-siskova"},
 "valentina-ryser":{wtaRank:263,wtaRankType:"Singles",age:25,titles:0,wonLost:"41 / 19",prizeMoney:"32 760 $",careerHigh:"213",birthDate:"22 mars 2001",height:"—",wtaUrl:"https://www.wtatennis.com/players/327219/valentina-ryser"},
 "fiona-crawley":{wtaRank:249,wtaRankType:"Singles",age:24,titles:0,wonLost:"20 / 10",prizeMoney:"94 005 $",wtaUrl:"https://www.wtatennis.com/players/327781/fiona-crawley"},
 "martha-matoula":{wtaRank:253,wtaRankType:"Doubles",age:29,titles:0,wonLost:"12 / 12",prizeMoney:"30 854 $",careerHigh:"296",birthDate:"26 avril 1997",height:"—",wtaUrl:"https://www.wtatennis.com/players/321132/martha-matoula"},
 "britt-du-pree":{wtaRank:244,wtaRankType:"Doubles",age:19,titles:0,wonLost:"17 / 5",prizeMoney:"25 824 $",wtaUrl:"https://www.wtatennis.com/players/333784/britt-du-pree"},
 "manon-leonard":{wtaRank:335,wtaRankType:"Singles",age:25,titles:0,wonLost:"12 / 23",prizeMoney:"71 208 $",careerHigh:"176",birthDate:"20 janvier 2001",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/325794/manon-leonard"},
 "sahaja-yamalapalli":{wtaRank:341,wtaRankType:"Singles",age:25,titles:0,wonLost:"25 / 21",prizeMoney:"23 391 $",careerHigh:"284",birthDate:"29 octobre 2000",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/331152/sahaja-yamalapalli"},
 "naiktha-bains":{wtaRank:370,wtaRankType:"Singles",age:28,titles:0,wonLost:"22 / 13",prizeMoney:"14 442 $",wtaUrl:"https://www.wtatennis.com/players/319962/naiktha-bains"},
 "yasmine-mansouri":{wtaRank:316,wtaRankType:"Doubles",age:25,titles:0,wonLost:"16 / 9",prizeMoney:"18 675 $",wtaUrl:"https://www.wtatennis.com/players/325188/yasmine-mansouri"},
 "tiphanie-lemaitre":{wtaRank:205,wtaRankType:"Doubles",age:26,titles:0,wonLost:"19 / 12",prizeMoney:"33 722 $",wtaUrl:"https://www.wtatennis.com/players/324972/tiphanie-lemaitre"},
 "amandine-hesse":{wtaRank:420,wtaRankType:"Singles",age:33,titles:0,wonLost:"17 / 17",prizeMoney:"29 708 $",careerHigh:"154",birthDate:"16 janvier 1993",height:"5' 4\" (1,64 m)",birthPlace:"Montauban, France",wtaUrl:"https://www.wtatennis.com/players/315148/amandine-hesse"},
 "lucie-nguyen-tan":{wtaRank:311,wtaRankType:"Doubles",age:23,titles:0,wonLost:"18 / 14",prizeMoney:"18 178 $",wtaUrl:"https://www.wtatennis.com/players/329092/lucie-nguyen-tan"},
 "laura-hietaranta":{wtaRank:263,wtaRankType:"Doubles",age:22,titles:0,wonLost:"14 / 12",prizeMoney:"19 707 $",wtaUrl:"https://www.wtatennis.com/players/329759/laura-hietaranta"},
 "hannah-klugman":{wtaRank:439,wtaRankType:"Singles",age:17,titles:0,wonLost:"25 / 20",prizeMoney:"131 539 $",careerHigh:"365",birthDate:"18 février 2009",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/333440/hannah-klugman"},
 "charlotte-narti":{wtaRank:1200,wtaRankType:"Singles",age:16,titles:0,wonLost:"13 / 10",prizeMoney:"2 236 $",wtaUrl:"https://www.wtatennis.com/players/336434/charlotte-narti"},
 "stefaniya-pushkar":{wtaRank:962,wtaRankType:"Singles",age:19,titles:0,wonLost:"6 / 16",prizeMoney:"2 757 $",wtaUrl:"https://www.wtatennis.com/players/334003/stefaniya-pushkar"},
 "anastasiia-firman":{wtaRank:368,wtaRankType:"Doubles",age:19,titles:0,wonLost:"18 / 13",prizeMoney:"11 587 $",wtaUrl:"https://www.wtatennis.com/players/332577/anastasiia-firman"},
 "hanna-bougouffa":{wtaRank:1326,wtaRankType:"Singles",age:22,titles:0,wonLost:"6 / 7",prizeMoney:"1 216 $",wtaUrl:"https://www.wtatennis.com/players/330539/hanna-bougouffa"},
 "gyeong-seo-lee":{wtaRank:727,wtaRankType:"Singles",age:21,titles:0,wonLost:"26 / 8",prizeMoney:"8 607 $",wtaUrl:"https://www.wtatennis.com/players/332132/gyeong-seo-lee"},
 "carson-tanguilig":{wtaRank:436,wtaRankType:"Doubles",age:23,titles:0,wonLost:"14 / 10",prizeMoney:"11 196 $",wtaUrl:"https://www.wtatennis.com/players/327868/carson-tanguilig"},
 "vicky-van-de-peer":{wtaRank:1291,wtaRankType:"Singles",age:25,titles:0,wonLost:"4 / 6",prizeMoney:"1 344 $",wtaUrl:"https://www.wtatennis.com/players/327535/vicky-van-de-peer"},
 "carolin-raschdorf":{wtaRank:871,wtaRankType:"Singles",age:20,titles:0,wonLost:"12 / 22",prizeMoney:"4 411 $",wtaUrl:"https://www.wtatennis.com/players/330706/carolin-raschdorf"},
 "sachia-vickery":{wtaRank:619,wtaRankType:"Singles",age:31,titles:0,wonLost:"3 / 10",prizeMoney:"43 061 $",careerHigh:"73",birthDate:"11 mai 1995",height:"1,63 m",birthPlace:"Miramar, Floride, États-Unis",wtaUrl:"https://www.wtatennis.com/players/317443/sachia-vickery"},
 "luisa-hrda":{wtaRank:993,wtaRankType:"Doubles",age:26,titles:0,wonLost:"8 / 9",prizeMoney:"2 700 $",wtaUrl:"https://www.wtatennis.com/players/323509/luisa-hrda"},
 "carmen-lopez-martinez":{wtaRank:844,wtaRankType:"Singles",age:21,titles:0,wonLost:"7 / 13",prizeMoney:"3 884 $",wtaUrl:"https://www.wtatennis.com/players/330508/carmen-lopez-martinez"},
 "mathilde-lollia":{wtaRank:615,wtaRankType:"Doubles",age:26,titles:0,wonLost:"5 / 8",prizeMoney:"7 673 $",wtaUrl:"https://www.wtatennis.com/players/328261/mathilde-lollia"},
 "katarina-kujovic":{wtaRank:1026,wtaRankType:"Singles",age:19,titles:0,wonLost:"13 / 16",prizeMoney:"3 076 $",wtaUrl:"https://www.wtatennis.com/players/335175/katarina-kujovic"},
 "marine-szostak":{wtaRank:738,wtaRankType:"Singles",age:24,titles:0,wonLost:"9 / 11",prizeMoney:"3 698 $",wtaUrl:"https://www.wtatennis.com/players/327011/marine-szostak"},
 "berta-bonardi":{wtaRank:667,wtaRankType:"Singles",age:31,titles:0,wonLost:"8 / 17",prizeMoney:"6 552 $",wtaUrl:"https://www.wtatennis.com/players/319314/berta-bonardi"},
 "seda-baslilar":{wtaRank:1014,wtaRankType:"Singles",age:18,titles:0,wonLost:"11 / 10",prizeMoney:"938 $",wtaUrl:"https://www.wtatennis.com/players/334583/seda-baslilar"},
 "paula-cembranos":{wtaRank:753,wtaRankType:"Singles",age:22,titles:0,wonLost:"21 / 15",prizeMoney:"5 735 $",wtaUrl:"https://www.wtatennis.com/players/332208/paula-cembranos"},
 "clara-vlasselaer":{wtaRank:672,wtaRankType:"Singles",age:25,titles:0,wonLost:"23 / 16",prizeMoney:"6 526 $",wtaUrl:"https://www.wtatennis.com/players/328130/clara-vlasselaer"},
 "daniela-vismane":{wtaRank:1042,wtaRankType:"Singles",age:26,titles:0,wonLost:"12 / 14",prizeMoney:"4 540 $",wtaUrl:"https://www.wtatennis.com/players/324595/daniela-vismane"},
 "lian-tran":{wtaRank:198,wtaRankType:"Doubles",age:24,titles:0,wonLost:"14 / 14",prizeMoney:"6 949 $",careerHigh:"329",birthDate:"19 juillet 2002",height:"—",birthPlace:"—",wtaUrl:"https://www.wtatennis.com/players/327527/lian-tran"},
 "demi-tran":{wtaRank:314,wtaRankType:"Doubles",age:25,titles:0,wonLost:"17 / 14",prizeMoney:"11 806 $",wtaUrl:"https://www.wtatennis.com/players/329458/demi-tran"},
 "ashmitha-easwaramurthi":{wtaRank:977,wtaRankType:"Doubles",age:37,titles:0,wonLost:"6 / 12",prizeMoney:"4 250 $",wtaUrl:"https://www.wtatennis.com/players/313983/ashmitha-easwaramurthi"},
 "naoko-eto":{wtaRank:1276,wtaRankType:"Singles",age:41,titles:0,wonLost:"2 / 12",prizeMoney:"3 023 $",wtaUrl:"https://www.wtatennis.com/players/312180/naoko-eto"},
 "kim-chiarello":{wtaRank:1004,wtaRankType:"Singles",age:22,titles:0,wonLost:"3 / 7",prizeMoney:"1 113 $",wtaUrl:"https://www.wtatennis.com/players/335306/kim-chiarello"}
};
const careerEarnings:Record<string,string>={"greet-minnen":"3 461 222 $","tessah-andrianjafitrimo":"673 518 $","celine-naef":"572 934 $","jaqueline-cristian":"3 350 510 $","mihaela-buzarnescu":"2 791 287 $","veronika-podrez":"182 462 $","martyna-kubka":"196 903 $","julia-avdeeva":"346 887 $","anna-siskova":"617 159 $","valentina-ryser":"269 082 $","fiona-crawley":"293 937 $","martha-matoula":"126 043 $","britt-du-pree":"46 585 $","manon-leonard":"374 266 $","sahaja-yamalapalli":"122 335 $","naiktha-bains":"529 240 $","yasmine-mansouri":"156 239 $","tiphanie-lemaitre":"145 586 $","lucie-nguyen-tan":"100 118 $","laura-hietaranta":"98 549 $","hannah-klugman":"304 921 $","ayana-akli":"203 312 $","polina-iatcenko":"299 765 $","lucia-cortez-llorca":"125 481 $","daniela-vismane":"156 463 $"};
export const players:Player[]=Array.from(new Map([wildcard,...direct,...officialQualifiers,...historicChampions].map(p=>{const key=slugify(p.name);const v={...p,...profiles[key],...wtaProfiles[key]};const completed={...v,birthDate:v.birthDate??"Non publié",birthPlace:v.birthPlace??"Non publié",height:v.height??"Non publié",careerHigh:v.careerHigh??"Non publié",titles:v.titles??0,wonLost:v.wonLost??"Non publié",seasonPrizeMoney:v.prizeMoney,prizeMoney:careerEarnings[key]??v.careerPrizeMoney??"Non publié"};return[key,completed]})).values());
export const getPlayer=(slug:string)=>players.find(p=>slugify(p.name)===slug);
export const getPlayerByName=(name:string)=>players.find(p=>slugify(p.name)===slugify(name));
