import { ArrowRight, Trophy, Users } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { FlagIcon } from "@/components/flag-icon";
import { editions } from "@/lib/history";
import { slugify } from "@/lib/players";

const historicCodes: Record<string, string> = { "Greet Minnen":"BEL", "Petra Marčinko":"CRO", "Manon Léonard":"FRA", "Tessah Andrianjafitrimo":"FRA", "Céline Naef":"SUI", "Alina Korneeva":"RUS", "Jaqueline Cristian":"ROU", "Magali Kempen":"BEL", "Mihaela Buzărnescu":"ROU", "Anna Bondár":"HUN", "Naiktha Bains":"GBR", "Rutuja Bhosale":"IND", "Polina Iatcenko":"N/C", "Sofya Lansere":"RUS", "Lina Glushko":"ISR", "Anastasia Tikhonova":"RUS", "Julia Avdeeva":"RUS", "Ekaterina Maklakova":"RUS", "Fiona Ferro":"FRA", "Maryna Kolb":"UKR", "Nadiia Kolb":"UKR", "Freya Christie":"GBR", "Ali Collins":"GBR", "Weronika Falkowska":"POL", "Sarah Beth Grey":"GBR", "Robin Anderson":"USA", "Amandine Hesse":"FRA", "Estelle Cascino":"FRA" };
function HistoricPlayer({ name, link = false }: { name: string; link?: boolean }) { const code = historicCodes[name] || "N/C"; const content = <span className="inline-flex items-center gap-2 align-middle"><FlagIcon code={code}/><span><b>{name}</b><small className="ml-1 text-[10px] font-black text-[#68766f]">{code}</small></span></span>; return link ? <a href={`/joueuses/${slugify(name)}`} className="hover:text-[#197c57]">{content}</a> : content; }
function Pair({ names }: { names: string }) { return <span className="flex flex-wrap items-center gap-1">{names.split(" / ").map((name, i) => <span key={name}><HistoricPlayer name={name}/>{i < names.split(" / ").length - 1 && <span className="mx-1 text-[#68766f]">/</span>}</span>)}</span>; }

export default function History() { return <main><SiteHeader/><div className="mx-auto max-w-[1280px] px-5 py-12"><p className="eyebrow">Depuis 2021</p><h1 className="page-title">Histoire du tournoi</h1><p className="intro">Toutes les éditions, les championnes en simple et en double, et le parcours match par match de chaque lauréate du simple.</p><div className="mt-10 space-y-5">{editions.map((e) => <article key={e.year} className="grid overflow-hidden rounded-[1.75rem] border border-[#dce3dd] bg-white lg:grid-cols-[180px_1fr]"><div className="grid place-items-center bg-[#0b3427] p-7 text-white"><div className="text-center"><small className="text-[#d9f13b]">{e.category}</small><b className="block text-5xl">{e.year}</b></div></div><div className="grid gap-6 p-6 md:grid-cols-2 md:p-8"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#197c57]"><Trophy size={15}/> Simple</p><div className="mt-3 text-2xl font-black"><HistoricPlayer name={e.single.name} link/></div><p className="mt-3 text-sm text-[#68766f]">Finale : {e.single.score} face à <HistoricPlayer name={e.single.runnerUp}/></p></div><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#197c57]"><Users size={15}/> Double</p><div className="mt-3 text-lg font-black"><Pair names={e.doubles.names}/></div><p className="mt-3 text-sm text-[#68766f]">Finale : {e.doubles.score} face à <Pair names={e.doubles.runnerUp}/></p></div><a href={`/historique/${e.year}`} className="inline-flex items-center gap-2 font-bold md:col-span-2">Revoir l’édition et le parcours <ArrowRight size={17}/></a></div></article>)}</div></div><SiteFooter/></main>; }
